name: Release Docker Image

on:
  release:
    types: [published]

jobs:
  docker:
    name: Build and push Docker images
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get tag name
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            kitos9112/terragrunt-gitlab-cicd-config:latest
            kitos9112/terragrunt-gitlab-cicd-config:${{ env.TAG }}
            ghcr.io/kitos9112/terragrunt-gitlab-cicd-config:latest
            ghcr.io/kitos9112/terragrunt-gitlab-cicd-config:${{ env.TAG }}
